version: "3"
services:
  timmy:
    image: nginx:alpine
    working_dir: /application
    ports:
      - "80:80"
    volumes:
      - .:/application
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  db:
    image: mysql
    volumes:
      - timmy_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=timmy
      - MYSQL_HOST=127.0.0.1
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: timmy
    working_dir: /application
    volumes:
      - .:/application
      - ./.docker/php/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    links:
      - db

volumes:
  timmy_db:
